'use client';

interface AiWarningModalProps {
  onConfirm: () => void;
  onDismiss: () => void;
}

export function AiWarningModal({ onConfirm, onDismiss }: AiWarningModalProps) {
  return (
    <div className="fixed inset-0 bg-black/50 z-[99999] flex items-center justify-center p-4">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-md w-full p-6 relative z-[100000]">
        <div className="mb-4 text-center">
          <div className="flex justify-center mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-14 w-14 text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-2" dir="ltr">AI Analysis Disclaimer</h3>
          <div className="text-gray-700 dark:text-gray-300" dir="ltr">
            <p className="mb-2">
              The AI suggestions provided are not always accurate and should be taken with a grain of salt.
            </p>
            <p className="mb-2">
              These suggestions are generated by an AI model that may misinterpret context or miss cultural nuances.
            </p>
            <p className="font-semibold">
              Always use your own judgment when deciding whether to accept AI suggestions.
            </p>
          </div>
        </div>
        <div className="flex justify-center gap-4">
          <button
            onClick={onDismiss}
            className="px-4 py-2 bg-gray-200 hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200 rounded-md transition-colors"
          >
            إلغاء
          </button>
          <button
            onClick={onConfirm}
            className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-md transition-colors"
          >
            فهمت، تشغيل تحليل الذكاء الاصطناعي
          </button>
        </div>
      </div>
    </div>
  );
}
